### ISSUE TITLE
Infinispan Operator might be ignoring custom secrets

### ISSUE THREAD

**Issue by ricardozanini** [infinispan/infinispan-operator#211] opened 2019-11-12 19:04 UTC
Hi!

I'm trying the [credentials example](https://infinispan.org/infinispan-operator/master/documentation/asciidoc/titles/operator.html#creating_auth_clusters-create_cluster) on `1.0.1` (Openshift 4.1, crc), and it seems that the operator is ignoring the `security.endpointSecret` spec. 

This is the actual status of a deployed Infinispan resource:

```yaml
Name:         example-infinispan
Namespace:    kogito-e2e
Labels:       <none>
Annotations:  <none>
API Version:  infinispan.org/v1
Kind:         Infinispan
Metadata:
  Creation Timestamp:  2019-11-12T18:53:39Z
  Generation:          1
  Resource Version:    1008643
  Self Link:           /apis/infinispan.org/v1/namespaces/kogito-e2e/infinispans/example-infinispan
  UID:                 bd3ac38a-057d-11ea-bacb-52fdfc072182
Spec:
  Replicas:  1
  Security:
    Endpoint Secret Name:  connect-secret
Status:
  Conditions:
    Message:  View: example-infinispan-0-44992
    Status:   True
    Type:     wellFormed
  Security:
    Endpoint Encryption:
      Cert Secret Name:  
      Cert Service:      
      Type:              
    Endpoint Secret:     <--------- BLANK
  Stateful Set Name:     example-infinispan
Events:                  <none>
```
And also, it's generating the secret even if I have the secret deployed in my cluster, e.g. `resource-name-generated-secret`. Looking at the code, it seems that it's copying from the given secret to an owned operator secret resource. Why not having the given secret bind to the StatefulSet instead of copying it?

Despite that, the generated secret `identities.yaml` is different from the given one.

Given:
```yaml
apiVersion: v1
data:
  identities.yaml: Y3JlZGVudGlhbHM6Ci0gdXNlcm5hbWU6IGRldmVsb3BlcgogIHBhc3N3b3JkOiBjaGFuZ2VtZQotIHVzZXJuYW1lOiBvcGVyYXRvcgogIHBhc3N3b3JkOiBjaGFuZ2VtZXRvbw==
kind: Secret
metadata:
  creationTimestamp: "2019-11-12T18:49:25Z"
  name: connect-secret
  namespace: kogito-e2e
  resourceVersion: "1007672"
  selfLink: /api/v1/namespaces/kogito-e2e/secrets/connect-secret
  uid: 25cfa3e8-057d-11ea-bacb-52fdfc072182
type: Opaque
```
Generated:
```yaml
apiVersion: v1
data:
  identities.yaml: Y3JlZGVudGlhbHM6Ci0gdXNlcm5hbWU6IGRldmVsb3BlcgogIHBhc3N3b3JkOiBSaDI2NE4zMUw0ajRFMlhmCi0gdXNlcm5hbWU6IG9wZXJhdG9yCiAgcGFzc3dvcmQ6IDhkdVNpWkZvVXJLZEhGaEMK
kind: Secret
metadata:
  creationTimestamp: "2019-11-12T18:53:39Z"
  name: example-infinispan-generated-secret
  namespace: kogito-e2e
  ownerReferences:
  - apiVersion: infinispan.org/v1
    blockOwnerDeletion: true
    controller: true
    kind: Infinispan
    name: example-infinispan
    uid: bd3ac38a-057d-11ea-bacb-52fdfc072182
  resourceVersion: "1008529"
  selfLink: /api/v1/namespaces/kogito-e2e/secrets/example-infinispan-generated-secret
  uid: bd3b6f35-057d-11ea-bacb-52fdfc072182
type: Opaque
```

It seems that even if I provide a secret, the operator is generating a new one with random password for `developer` and `operator` users. :(

**Comment by Crumby** [comment] 2019-11-13 09:26
@ricardozanini Have you tried using `endpointSecretName` instead `endpointSecret`? Docs are bit outdated atm. (cc @oraNod). See [design doc](https://github.com/infinispan/infinispan-operator/blob/master/doc/design.adoc) for more Infinispan CR references.

**Comment by oraNod** [comment] 2019-11-13 09:39
@ricardozanini as @Crumby mentioned the docs are a bit outdated. it should be `endpointSecretName` as [in the example cr](https://github.com/infinispan/infinispan-operator/blob/9fe5cbf27e4b51159ae18f430f8915cdfdd18c19/documentation/asciidoc/topics/yaml_examples/cr_minimal_with_auth.yaml#L8).

sorry you're hitting issues due to stale docs. we need to start refreshing the community site more regularly to keep up with the pace of changes.

in the meantime you can always build docs locally from source with asciidoctor:

`$ asciidoctor documentation/asciidoc/titles/operator.asciidoc`

**Comment by ricardozanini** [comment] 2019-11-13 23:54
Guys,

I didn't even notice this doc problem, since I'm integrating my operator with yours, thus using the [API directly](https://github.com/kiegroup/kogito-cloud-operator/pull/104/files?file-filters%5B%5D=.md&file-filters%5B%5D=.mod&file-filters%5B%5D=.sh&file-filters%5B%5D=.sum&file-filters%5B%5D=.txt&file-filters%5B%5D=.yaml&file-filters%5B%5D=No+extension#diff-6f6b93bfb748890c3dd0740851255020R108).

And I just double checked, and it's not working for me:

1. Created the given secret:

```
oc apply -f https://raw.githubusercontent.com/infinispan/infinispan-operator/master/deploy/cr/auth/connect_secret.yaml
```

2. Created the example instance:

```
cat cr_minimal_with_auth.yaml                                                                                   
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: example-infinispan
spec:
  replicas: 1
  security:
    endpointSecretName: connect-secret
```

Please note the `endpointSecretName`

3. The result CR:

```yaml
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  creationTimestamp: "2019-11-13T23:31:02Z"
  generation: 1
  name: example-infinispan
  namespace: kogito-olm
  resourceVersion: "1137229"
  selfLink: /apis/infinispan.org/v1/namespaces/kogito-olm/infinispans/example-infinispan
  uid: a801d5d9-066d-11ea-9650-52fdfc072182
spec:
  replicas: 1
  security:
    endpointSecretName: connect-secret <------------
status:
  conditions:
  - message: 'View: example-infinispan-0-57582'
    status: "True"
    type: wellFormed
  security:
    endpointEncryption:
      certSecretName: ""
      certService: ""
      type: ""
    endpointSecret: ""
  statefulSetName: example-infinispan
```

Also the status hasn't change, I guess that's because might be a leftover somewhere else.

4. Check for the secrets and you will see the generated one with a random password:

```
 oc get secret/example-infinispan-generated-secret -o yaml
apiVersion: v1
data:
  identities.yaml: Y3JlZGVudGlhbHM6Ci0gdXNlcm5hbWU6IGRldmVsb3BlcgogIHBhc3N3b3JkOiBCQVloblRvZ3JPZVlJNnk2Ci0gdXNlcm5hbWU6IG9wZXJhdG9yCiAgcGFzc3dvcmQ6IEg0SnA5U1RwUFBOaE9icGcK
kind: Secret
```

**Comment by galderz** [comment] 2019-11-29 16:49
@ricardozanini In `1.0.1` it should be `endpointSecretName`. Did you get this working in the end? 

That `identities.yaml` indeed contains random password information. Did you try deleting infinispan and re-creating it? Wondering if the issue is with updates.

**Comment by galderz** [comment] 2019-11-29 16:51
@rigazilla Could this be an issue as a result of having different name for `status.security.endpointSecret` and `spec.security.endpointSecretName`? I guess `status.security.endpointSecret` should be renamed to ``status.security.endpointSecretName` to align it properly.

**Comment by rigazilla** [comment] 2019-11-29 18:03
@ricardozanini I've tried to reproduce locally but everything works as expected here:
I've `spec.security.endpointSecretName` and `status.security.endpointSecretName` with the same value and both the secrets have the same `identities.yaml`

Please check the operator version you're running.

I agree that we should simplify this mechanism

**Comment by ricardozanini** [comment] 2019-12-02 14:45
@rigazilla no, I was using Infinispan 1.0.1 in this reproducer. I'll get back on this next week when I'll have more time.

**Comment by dmvolod** [comment] 2020-08-05 09:42
Closing as refactored code with #489 has extended with functionality

**Closed by dmvolod** 2020-08-05 09:42 UTC
